export const esc = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const label = value => String(value ?? '').replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase());
export const date = value => value && !Number.isNaN(Date.parse(value)) ? new Intl.DateTimeFormat('en-GB', {day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Colombo'}).format(new Date(value)) : 'Time unknown';
export const icon = (name, size=18) => `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({grid:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',pin:'<path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',check:'<path d="m5 12 4 4L19 6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',crew:'<path d="m14 4 6 6-5 5-6-6ZM3 21l8-8m4-9 2-2 5 5-2 2"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',reports:'<path d="M5 3h14v14H9l-4 4V3Z"/><path d="M9 7h6M9 11h4"/>',warn:'<path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v5m0 3v.1"/>'})[name] || ''}</svg>`;
export const priority = p => `<span class="priority ${esc(p)}"><i></i>${esc(label(p))}</span>`;
export const status = s => `<span class="status ${esc(s)}">${s==='completed'?icon('check',12):''}${esc(label(s))}</span>`;
const crewName = (crews,id) => crews.find(c=>c.id===id)?.name || 'Needs crew review';
export function operationsSummary(o) {
 return `<div class="summary"><div><span class="eyebrow">OPEN PROBLEMS</span><strong>${o.openProblems}<small>to work through</small></strong></div><div><span class="eyebrow">REPORTS → PROBLEMS</span><strong>${o.sourceReportCount}<span class="compression-arrow">→</span>${o.distinctProblems}</strong><span class="metric-note">Across published workspace records</span></div><div><span class="eyebrow">HIGH PRIORITY · OPEN</span><strong class="red-ink">${o.highPriority}<small>review first</small></strong></div><div><span class="eyebrow">COMPLETED</span><strong>${o.counts.completed || 0}<small>in this workspace</small></strong></div></div>`;
}
export function crewStrip(crews) {
 return `<div class="crew-strip">${crews.map((c,i)=>`<button class="crew-tile" data-action="crew" data-id="${esc(c.id)}"><span class="crew-number">0${i+1}</span><span class="crew-tile-text"><strong>${esc(c.name)}</strong><span>${c.assignedCount+c.inProgressCount ? `${c.assignedCount} assigned · ${c.inProgressCount} in progress` : 'Available · no active assignments'}</span></span><span class="availability ${c.inProgressCount?'working':''}"></span>${icon('arrow',16)}</button>`).join('')}</div>`;
}
/** @param {import('./domain').Problem} p */
export function problemRow(p, crews) {
 const overridden=p.decision?.priorityOverridden;
 return `<button class="problem-row" data-action="detail" data-id="${esc(p.id)}"><div class="rank-cell">${priority(p.priority)}<span class="rank-reason">${overridden?'Maya’s override':esc(p.priorityRecommendation.factors[0]?.label || p.priorityRecommendation.explanation)}</span></div><div class="problem-cell"><div class="row-title">${esc(p.title)}</div><div class="location-line">${icon('pin',13)}${esc(p.location?.label || 'Location unresolved')}${p.location?.detail?`<span>· ${esc(p.location.detail)}</span>`:''}</div><p class="row-description">${esc(p.description)}</p><div class="row-tags"><span>${esc(label(p.workType))}</span>${p.analysis?.state==='needs_review'?'<span class="review-tag">Grouping needs review</span>':p.analysis?.state==='pending'?'<span class="review-tag">Analysis pending</span>':p.analysis?.state==='failed'?'<span class="review-tag">Analysis failed</span>':''}</div></div><div class="report-cell"><strong>${p.reportCount}</strong><span>report${p.reportCount===1?'':'s'}</span></div><div class="recommendation-cell"><span class="tiny-label">${p.assignment?'MAYA’S ASSIGNMENT':'RECOMMENDED'}</span><strong>${esc(crewName(crews,p.assignment?.crewId || p.crewRecommendation.crewId))}</strong>${p.decision?.crewOverridden?'<span class="human-note">Crew override</span>':''}</div><div class="status-cell">${status(p.status)}${icon('arrow',16)}</div></button>`;
}
export function problemQueue(page, crews) {
 if (!page.items.length) return `<div class="empty-state">${icon('check',32)}<h3>No problems in this view</h3><p>Upload and process the three CSVs to publish problems, or try another filter.</p><button class="button secondary" data-action="reset">Clear filters</button></div>`;
 return `<div class="queue-head"><span>PRIORITY / WHY</span><span>OPERATIONAL PROBLEM</span><span>EVIDENCE</span><span>CREW</span><span>STATUS</span></div>${page.items.map(p=>problemRow(p,crews)).join('')}`;
}
export function pagination(page) {
 return `<div class="pagination"><span>${page.total ? `${(page.page-1)*page.pageSize+1}–${Math.min(page.page*page.pageSize,page.total)} of ${page.total} problems` : '0 problems'}</span><div><button class="button subtle" data-action="prev" ${page.page<=1?'disabled':''}>← Previous</button><span>Page ${page.page}</span><button class="button subtle" data-action="next" ${page.page*page.pageSize>=page.total?'disabled':''}>Next →</button></div></div>`;
}
export function crewWork(page, crews, selected) {
 const crew=crews.find(c=>c.id===selected);
 return `<div class="crew-view-heading"><div><span class="eyebrow">CREW WORKLIST</span><h2>${esc(crew?.name || 'Choose a crew')}</h2><p>${esc(crew?.description || '')} · Shared with Maya</p></div><span class="badge">${page.total} matching jobs</span></div>${!page.items.length?'<div class="empty-state"><h3>No work in this view</h3><p>Check Completed for finished jobs, or wait for Maya to dispatch more work.</p></div>':`<div class="crew-jobs">${page.items.map(p=>`<article class="crew-job"><div class="job-top">${priority(p.priority)}${status(p.status)}</div><h3>${esc(p.title)}</h3><div class="location-line">${icon('pin',15)}${esc(p.location?.label || 'Location unresolved')}</div><p>${esc(p.description)}</p><div class="job-context">${p.reportCount} supporting reports · ${esc(label(p.workType))}${p.decision?.crewOverridden?' · Crew chosen by Maya':''}</div><div class="job-actions"><button class="button secondary" data-action="detail" data-id="${esc(p.id)}">View evidence & context</button>${p.status!=='completed'?`<button class="button primary" data-action="transition" data-id="${esc(p.id)}" data-revision="${p.revision}" data-status="${p.status==='assigned'?'in_progress':'completed'}" data-crew="${esc(p.assignment?.crewId)}">${p.status==='assigned'?'Start work':'Mark completed'} ${icon('arrow',16)}</button>`:'<span class="completion-note">'+icon('check',16)+' Completed '+date(p.assignment?.completedAt)+'</span>'}</div></article>`).join('')}</div>`}`;
}
export function problemDetail(p,crews,mode) {
 const rec=p.crewRecommendation;const decision=p.decision;
 return `<header class="detail-header"><div><span class="eyebrow">PROBLEM / ${esc(p.id.slice(2,10).toUpperCase())}</span><div class="detail-badges">${priority(p.priority)}${status(p.status)}</div></div><button class="icon-button" data-action="close" aria-label="Close problem details">${icon('close',22)}</button></header><div class="detail-scroll"><h2 id="detail-title">${esc(p.title)}</h2><div class="detail-location">${icon('pin',17)}<span>${esc(p.location?.label || 'Location unresolved')}${p.location?.detail?`<small>${esc(p.location.detail)}</small>`:''}</span></div>${p.description.length>700?`<p class="actionable-description">${esc(p.description.slice(0,450))}…</p><details class="full-description"><summary>Read full description</summary><p class="actionable-description">${esc(p.description)}</p></details>`:`<p class="actionable-description">${esc(p.description)}</p>`}<div class="detail-meta"><span>${icon('reports',15)} ${p.reportCount} supporting reports</span><span>First ${date(p.firstReportedAt)}</span><span>Latest ${date(p.latestReportedAt)}</span></div><div class="uncertainty"><strong>${icon('warn',16)} ${p.analysis?.state==='failed'?'Analysis failed':p.analysis?.state==='pending'?'Analysis pending':'Check before dispatch'}</strong><ul>${(p.analysis?.uncertainties || ['No analysis explanation available.']).map(u=>`<li>${esc(u)}</li>`).join('')}</ul></div>
 <section class="detail-section"><div class="section-title"><h3>Why this priority</h3><span class="tiny-label">SYSTEM RECOMMENDATION</span></div><p class="muted">${esc(label(p.priorityRecommendation.level))} · ${esc(p.priorityRecommendation.explanation)}</p><div class="factors">${p.priorityRecommendation.factors.map(f=>`<div><span><strong>${esc(f.label)}</strong><small>${esc(f.detail)}</small></span></div>`).join('')}</div>${decision?.priorityOverridden?`<div class="decision-note"><strong>Maya set ${esc(label(p.priority))} priority</strong><p>${esc(decision.priorityReason)}</p></div>`:''}
 ${mode==='maya'&&p.status!=='completed'?`<form id="priority-form"><div class="form-row"><label>Operational priority<select name="priority">${['high','medium','low'].map(v=>`<option ${p.priority===v?'selected':''} value="${v}">${label(v)}</option>`).join('')}</select></label><button class="button secondary" type="submit">Save priority</button></div><label class="small-label">Reason if overriding the recommendation<input name="reason" maxlength="500" value="${esc(decision?.priorityReason || '')}" placeholder="What changes the urgency?" /></label></form>`:''}</section>
 <section class="detail-section"><div class="section-title"><h3>${p.assignment?'Dispatch decision':'Recommended crew'}</h3><span class="tiny-label">${p.assignment?'MAYA’S DECISION':'SYSTEM RECOMMENDATION'}</span></div><div class="recommended-crew">${icon('crew',24)}<div><strong>${esc(crewName(crews,rec.crewId))}</strong><p>${esc(rec.reason)}</p>${rec.confidence===null?'':`<small>Backend confidence estimate: ${Math.round(rec.confidence*100)}%</small>`}</div></div>${p.assignment?`<div class="decision-note"><strong>Assigned to ${esc(crewName(crews,p.assignment.crewId))}</strong><p>${decision?.crewOverridden?'Human override · '+esc(decision.crewReason):'Recommendation accepted by Maya'} · ${date(p.assignment.assignedAt)}</p></div>`:''}
 ${mode==='maya'&&['unreviewed','assigned'].includes(p.status)?`<form id="assignment-form"><label>Dispatch to<select name="crewId" required><option value="">Choose a crew</option>${crews.map(c=>`<option value="${esc(c.id)}" ${(p.assignment?.crewId || rec.crewId)===c.id?'selected':''}>${esc(c.name)} · ${c.assignedCount+c.inProgressCount} active</option>`).join('')}</select></label>${!p.location?'<label>Confirmed location<input name="location" maxlength="200" required placeholder="Enter an actionable site or address"></label>':''}<label>Reason if choosing another crew<input name="reason" maxlength="500" value="${esc(decision?.crewReason || '')}" placeholder="Confirm why this crew can handle the work"></label><label class="checkbox-label"><input type="checkbox" name="reviewConfirmed" required><span>I’ve checked the location, grouping and crew capability.</span></label><button class="button primary full-width" type="submit">${p.assignment?'Update assignment':'Assign work'} ${icon('arrow',18)}</button><p class="form-hint">Only your decision dispatches work. Saved to the shared workspace.</p></form>`:''}</section>
 <section class="detail-section"><h3>Location & asset context</h3><p class="muted">Context supplied by the backend; review the stated relationship to this problem.</p>${p.assets?.length?`<div class="context-list">${p.assets.map(a=>`<div><strong>${esc(label(a.type))}</strong><span>${esc(a.id)} · ${esc(a.roadClass || 'Classification unknown')} · ${esc(a.ward || 'Ward unknown')}</span>${a.facility?`<small>${esc(a.facility)}${a.distanceMeters!=null?` · reported asset-to-facility distance ${a.distanceMeters} m`:''}</small>`:''}<small>${esc(a.relationship)}</small></div>`).join('')}</div>`:'<p class="no-context">No matching asset context available.</p>'}</section>
 <section class="detail-section"><h3>Related recent work <span class="count">${p.recentJobs?.length || 0}</span></h3><p class="muted">Related work is context, not proof that the current problem is resolved.</p>${p.recentJobs?.length?`<div class="context-list">${p.recentJobs.map(j=>`<div><strong>${esc(j.workType)}</strong><span>${date(j.completedAt)} · ${esc(j.crewName)}</span><small>${esc(j.notes || 'No completion notes provided.')} · ${esc(j.relationship)}</small></div>`).join('')}</div>`:'<p class="no-context">No related jobs are available.</p>'}</section>
 <section class="detail-section"><button class="evidence-toggle" data-action="evidence" aria-expanded="false">${icon('reports',18)} Source resident reports <span class="count">${p.reportCount}</span><span class="push-right">Show ↓</span></button><p class="muted">Resident contact details are excluded from this evidence view.</p><div id="evidence" hidden></div></section><div id="panel-error" role="alert"></div></div><footer class="detail-footer"><span>${icon('clock',14)} Persistent shared record · revision ${p.revision}</span><button class="button subtle" data-action="reload-detail">Refresh details</button></footer>`;
}
export function sourceReports(page) {
 return `${page.items.map(r=>`<article class="source-report"><header><strong>${esc(r.reference)}</strong><span>${esc(label(r.channel))} · ${date(r.receivedAt)}</span></header><p>${esc(r.description)}</p><small>${esc(r.location || 'No location supplied')}</small></article>`).join('')}<div class="evidence-pagination"><button class="button subtle" data-action="evidence-prev" ${page.page<=1?'disabled':''}>← Previous</button><span>${page.page} / ${Math.max(1,Math.ceil(page.total/page.pageSize))}</span><button class="button subtle" data-action="evidence-next" ${page.page*page.pageSize>=page.total?'disabled':''}>Next →</button></div>`;
}
